/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CuButton: typeof import('./../src/components/cu-button/index.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    LineChart: typeof import('./../src/components/Charts/LineChart.vue')['default']
    Panel: typeof import('./../src/components/Panel/index.vue')['default']
    PieChart: typeof import('./../src/components/Charts/PieChart.vue')['default']
    Popover: typeof import('./../src/components/Popover/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sence: typeof import('./../src/components/Sence.vue')['default']
    SvgIcon: typeof import('./../src/components/svgIcon/index.vue')['default']
  }
}
